# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.2
  hooks:
  - id: commitizen
    stages: [commit-msg]
- repo: local
  hooks:
  - id: update-version-file
    name: Update Version file
    entry: python update_version.py
    language: python
    stages: [post-commit]
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    stages: ['commit']
